#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# Setup case
./Allrun.pre


#-- Run on single processor



runApplication $(getApplication)



#echo
#echo "creating files for paraview post-processing"
#echo
#paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
